# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'install Node.js in version 10.x'

- script: |
    npm install
    npm run build
  displayName: 'npm install and npm run build'

- task: Npm@1
  inputs:
    command: publish
    publishEndpoint: 'npmjs-th'
  displayName: 'npm publish'
